<a href="https://colab.research.google.com/github/mars241/DatasetP4/blob/main/AAM_WCS_Live_Coding_24_01_2023_Nettoyage_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Etape 1:  Téléchager le fichier "operations.csv" du SLACK le copier dans son google drive/ ou PC bureau!

#Methode1: importer un fichier ;CODE à exécuter exclusivement dans google colab: permet d'importer un fichier (ici csv):
#le code lancé, on vous invite à importer votre fichier depuis vôtre PC ou depuis google colab
from google.colab import files
uploaded = files.upload()  #/!\ A UTILISER QUE SUR GOOGLE COLAB

#Methode2: importer notre fichier "operation.csv" depuis vôtre PC (dans le dossier "downloard")
#df = pd.read_csv(r'C:/Users/marcia2/Downloads/operation.csv', sep = ',') #/!\ A REVOIR LA SYNTHAXE !

In [ ]:
from google.colab import  files

upload = files.upload()

Saving operations.csv to operations.csv

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime as dt

df_op = pd.read_csv('operations.csv', sep = ',')

#on vérifie le nombre de données
df_op.shape

(309, 5)

In [ ]:
df_op.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 308 entries, 0 to 308
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date_operation  308 non-null    object
 1   libelle         308 non-null    object
 2   montant         308 non-null    float64
 3   solde_avt_ope   308 non-null    float64
 4   categ           308 non-null    object
dtypes: float64(2), object(3)
memory usage: 14.4+ KB

In [ ]:
df_op.loc[106:108]

,date_operation,libelle,montant,solde_avt_ope,categ
106,2023-06-12,CARTE XX XX XX XX XX XX,-2.32,4669.51,AUTRE
107,2023-06-12,CARTE XX XX LES ANCIENS ROBINSON XX,-26.58,4667.19,COURSES
108,2023-06-12,CARTE XX XX CHEZ LUC XX,-9.20,4640.61,RESTAURANT

In [ ]:
#on vérifie les valeurs nulles
df_op.isna().sum()

#à cette étape: on a 2 valeurs manquantes sur la colonne "montant" et une sur la "categ"

date_operation    0
libelle           0
montant           2
solde_avt_ope     0
categ             1
dtype: int64

In [ ]:
#On affiche les deux valeurs nulles de la colonne montant
df_op[df_op.montant.isnull()]

,date_operation,libelle,montant,solde_avt_ope,categ
107,2023-06-12,CARTE XX XX LES ANCIENS ROBINSON XX,NaN,4667.19,COURSES
269,2023-09-11,CARTE XX XX XX XX,NaN,3401.93,AUTRE

In [ ]:
# Autrement
df_op[df_op['categ'].isna()] # Exécuter après les modifs d'en bas!

Empty DataFrame
Columns: [date_operation, libelle, montant, solde_avt_ope, categ]
Index: []

In [ ]:
#Nous allons remplir les cases de valeures nulles en mettant le montant de la précédente transaction
df_nul=df_op.loc[df_op.montant.isnull()]

for index in df_nul.index:
  df_op.loc[index, 'montant'] = df_op.loc[index+1, 'solde_avt_ope'] - df_op.loc[index, 'solde_avt_ope']

In [ ]:
# Autrement
df_op['solde_avt_ope'][107] - df_op['solde_avt_ope'][108]

26.579999999999927

In [ ]:
#Nous allons remplir les cases de valeures nulles en mettant le libelle de la précédente transaction
df_op[df_op.libelle.str.contains('PRELEVEMENT XX TELEPHONE')]

,date_operation,libelle,montant,solde_avt_ope,categ
8,2023-04-05,PRELEVEMENT XX TELEPHONE XX XX,-7.02,2056.02,FACTURE TELEPHONE
62,2023-05-09,PRELEVEMENT XX TELEPHONE XX XX,-7.02,4090.10,FACTURE TELEPHONE
102,2023-06-07,PRELEVEMENT XX TELEPHONE XX XX,-6.38,4688.91,FACTURE TELEPHONE
156,2023-07-06,PRELEVEMENT XX TELEPHONE XX XX,-36.48,3295.68,NaN
204,2023-08-07,PRELEVEMENT XX TELEPHONE XX XX,-7.46,3751.73,FACTURE TELEPHONE
260,2023-09-05,PRELEVEMENT XX TELEPHONE XX XX,-6.38,3453.96,FACTURE TELEPHONE
308,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

In [ ]:
# Autrement
df_op[df_op['libelle'].str.contains('PRELEVEMENT XX TELEPHONE')]

,date_operation,libelle,montant,solde_avt_ope,categ
8,2023-04-05,PRELEVEMENT XX TELEPHONE XX XX,-7.02,2056.02,FACTURE TELEPHONE
62,2023-05-09,PRELEVEMENT XX TELEPHONE XX XX,-7.02,4090.10,FACTURE TELEPHONE
102,2023-06-07,PRELEVEMENT XX TELEPHONE XX XX,-6.38,4688.91,FACTURE TELEPHONE
156,2023-07-06,PRELEVEMENT XX TELEPHONE XX XX,-36.48,3295.68,FACTURE TELEPHONE
204,2023-08-07,PRELEVEMENT XX TELEPHONE XX XX,-7.46,3751.73,FACTURE TELEPHONE
260,2023-09-05,PRELEVEMENT XX TELEPHONE XX XX,-6.38,3453.96,FACTURE TELEPHONE
308,2023-10-06,PRELEVEMENT XX TELEPHONE XX XX,-13.58,2413.58,FACTURE TELEPHONE

In [ ]:
#on remarque c'est le même libéllé donc on veut mettre également ' facture telephone'
df_op.categ.fillna("FACTURE TELEPHONE", inplace = True)

In [ ]:
# Autrement:
df_op['categ'].fillna('FACTURE TELEPHONE', inplace = True)

In [ ]:
#on vérifie qu'on n'ai plus de donnée manquante
df_op.isna().sum()

# à cette étape , on a plus de NA!

date_operation    0
libelle           0
montant           0
solde_avt_ope     0
categ             0
dtype: int64

In [ ]:
df_op[df_op.montant == df_op.montant.min()]

    date_operation            libelle  montant  solde_avt_ope  categ
199     2023-08-03  CARTE XX XX XX XX -15000.0        3797.35  AUTRE

In [ ]:
#On vérifie le montant de la précédente opération et de l'opération suivante
df_op.loc[198:200]

,date_operation,libelle,montant,solde_avt_ope,categ
198,2023-08-03,VIREMENT XX XX XX XX XX XX XX XX XX XX XX XX,676.00,3121.35,AUTRE
199,2023-08-03,CARTE XX XX XX XX,-15000.00,3797.35,AUTRE
200,2023-08-03,CARTE XX XX L'EPICERIE DEMBAS XX XX,-10.51,3782.96,AUTRE

In [ ]:
#il semblerait qu'il y ai une erreur dans les montant ligne 199 : effectivement le -15000 aurait dû etre -15, nous allons donc modifié le bdd
df_op.loc[199,'montant'] = -15.00 # mettre un seul = pour modifier

In [ ]:
df_op[df_op['montant'] == -15000]

Empty DataFrame
Columns: [date_operation, libelle, montant, solde_avt_ope, categ]
Index: []

In [ ]:
df_op.loc[198:200]

,date_operation,libelle,montant,solde_avt_ope,categ
198,2023-08-03,VIREMENT XX XX XX XX XX XX XX XX XX XX XX XX,676.00,3121.35,AUTRE
199,2023-08-03,CARTE XX XX XX XX,-15.00,3797.35,AUTRE
200,2023-08-03,CARTE XX XX L'EPICERIE DEMBAS XX XX,-10.51,3782.96,AUTRE

In [ ]:
df_op.loc[199,'montant'] = -15.00

In [ ]:
df_op.describe()

           montant  solde_avt_ope
count   308.000000     308.000000
mean      2.870584    3395.301071
std     176.090056     667.109412
min    -602.270000    1416.810000
25%     -20.047500    3010.737500
50%      -9.600000    3452.465000
75%      -2.715000    3787.232500
max    1071.600000    4709.310000

In [ ]:
#recherchons les doublons
df_op[df_op.duplicated(keep=False)]

,date_operation,libelle,montant,solde_avt_ope,categ
43,2023-04-25,CARTE XX XX LES ANCIENS ROBINSON XX,-32.67,3647.67,COURSES
44,2023-04-25,CARTE XX XX LES ANCIENS ROBINSON XX,-32.67,3647.67,COURSES

In [ ]:
#on supprime tous les doublons
df_op.drop_duplicates(inplace=True)

In [ ]:
df_op.loc[43:45]

,date_operation,libelle,montant,solde_avt_ope,categ
43,2023-04-25,CARTE XX XX LES ANCIENS ROBINSON XX,-32.67,3647.67,COURSES
45,2023-04-26,CARTE XX XX XX XX XX XX,-10.00,3615.00,AUTRE

In [ ]:
# supprimer les valeurs doubles:
df_op.drop_duplicates(inplace = True)